version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: intern-sit-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - /home/ubuntu/ssl:/ssl/
    networks:
      intern-sit-network:
        ipv4_address: 172.24.0.13
  db:
    image: mysql/mysql-server
    container_name: intern-sit-db
    restart: always
    env_file: ./.env.db
      
    expose:
      #running inside container
      - 3306
    networks:
      intern-sit-network:
        ipv4_address: 172.24.0.12
    volumes:
       #- ./db:/var/lib/mysql
       - ./mysqlinit:/docker-entrypoint-initdb.d/
    #    - ./init.sh:/init.sh
    # entrypoint: sh -c "/init.sh"
    # command: mysql -udbuser -phelloDEV371_
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - intern-sit-db
    environment:
      PMA_HOST: intern-sit-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:81
  intern-sit:
    depends_on:
      - db
    container_name: intern-sit-app
    restart: always
    # build:
    #   context: .
      #target: build
    # image: intern_sit:dev
    image: ghcr.io/int-371-09-17-78/intern-sit:1.0.0
    #volumes:
     # - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
     # - ./mysqlinit:/etc/ssl/certs/
    expose:
      #running inside container
      - 3333
    networks:
      intern-sit-network:
        ipv4_address: 172.24.0.11
networks:
  intern-sit-network:
    # external: true
    name: intern-sit-network
    ipam:
      config:
        - subnet: 172.24.0.0/16
      # - 9229:9229
    #env_file:
      #- .env
    #volumes:
      #- ./:/home/node/app/build
    #command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
